
export function AboutIDMS() {
  return (
    <>
      <section className="lg:relative px-6">
        <div className="mx-auto px-8 w-full max-w-screen-md pt-16 pb-20 text-left lg:text-left custom-bg">

          <div className="xl:pr-8">
            <h1 className="text-4xl mr-8 font-headings font-bold tracking-tight text-primary flex flex-col ">
              About IDMS
            </h1>
            <p className="mb-4 mt-3 text-base md:mt-8">
            Integrated Data Management System (IDMS) is a comprehensive and interoperable digital platform meticulously designed to facilitate seamless inter-governmental data sharing and the efficient dissemination of valuable data in the public domain, adhering to the FAIR principles.
            </p>
            <p>
            IDMS ensures the fairness, accessibility, interoperability, and reusability of data, providing a robust framework for secure and transparent data management. It is not a new standalone system; instead, it functions as a channel to connect data generated by existing digital systems, delivering standardized data to everyone.
            </p>
            <h1 className="text-xl mr-8 font-bold tracking-tight text-primary flex flex-col mt-16">
              High level fuctional overview
            </h1>
            <img src="/images/IDMSFunctional.svg" alt="Functional Diagram" className="mt-10"/>
          </div>
        </div>
      </section>
    </>
  )
}
