
const projects = [
  { imagePath: "/images/Logo.png", url: "https://data.birgunjmun.gov.np", heading: "Birgunj Metropolitan City", body: "Integrated Data Management System (IDMS)" },
  { imagePath: "/images/Logo.png", url: "https://data.tulsipurmun.gov.np", heading: "Tulsipur Sub-Metropolitan City", body: "Integrated Data Management System (IDMS)" },
  { imagePath: "/images/Logo.png",url: "https://data.janakpurmun.gov.np", heading: "Janakpurdham Sub-Metropolitan City", body: "Integrated Data Management System (IDMS)" },
  { imagePath: "/images/Logo.png",url: "https://data.lekbeshimun.gov.np", heading: "Lekbeshi Municipality", body: "Integrated Data Management System (IDMS)" },
  { imagePath: "/images/Logo.png",url: "https://data.shuddhodhan.oknp.org/", heading: "Shuddhodhan Rural Municipality", body: "Integrated Data Management System (IDMS)" }

]


export function Showcases() {
  return (
    <>
      <section className="lg:relative">
        <div className="mx-auto w-full max-w-screen-xl px-8 pt-16 pb-20 text-center lg:text-left custom-bg">
          <div className="xl:pr-8">
            <h1 className="mb-8 text-2xl mr-8 font-headings font-bold tracking-tight text-3xl flex flex-col">
              Showcases
            </h1>
            <p className="tracking-tight">
            IDMS serves as a central hub utilized by various agencies to aggregate data generated by different systems. Its purpose is to facilitate efficient data sharing among departments and to make valuable data accessible to the general public.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 w-5/6 gap-12 mt-10">
              {projects.map((item, index) => (
                <div
                key={index} 
                className="border-teal-300 border-2 mx-auto lg:mx-0 text-left  cursor-pointer hover:grayscale p-4 shadow-md "
                onClick={() => window.open(item.url, '_blank')}>
                  <img className="p-4 w-28" src={item.imagePath} alt="showcase idms" />
                  <div className="p-4 pt-0">
                    <h2 className="font-bold text-xl pb-4">{item.heading}</h2>
                    <p>{item.body}</p>
                  </div>
                  <span className="relative bottom-2 p-4 text-base">Learn More →</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  )
}